---
openapi: 3.0.3
info:
  title: your-bff
  version: "1.0"
paths:
  /entity/search:
    get:
      tags:
        - "Entity"
      operationId: search
      parameters:
        - name: page
          in: query
          schema:
            format: int32
            type: integer
        - name: pageSize
          in: query
          schema:
            format: int32
            type: integer
        - name: nameFilter
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchEntityResponse'
        "500":
          description: Internal Server Error
  
components:
  schemas:
    SearchEntityResponse:
      type: object
      properties:
        totalElements:
          type: integer
          format: int64
        entities:
          type: array
          items:
            $ref: '#/components/schemas/Entity'

    Entity:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        